version: "3"
services:
  postgres:
    image: "postgres"
    container_name: "express_postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: express
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./db/data:/var/lib/postgresql/data
